[package]
name = "azure_script"
version = "0.1.4"
edition = "2021"
description = "A brand new way to write azure infrastructure as code"
license = "MIT"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"

[package.metadata.docs.rs]
# Do not build documentation for dependencies
no-deps = true
